apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnx-private-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hvnhi-web
  template:
    metadata:
      labels:
        app: hvnhi-web
    spec:
      containers:
        - name: hvnhi-web
          image: hvnhi/dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 2

--- 
apiVersion: v1
kind: Service
metadata:
  name: hvnhi-web
spec:
  ports:
    - name: app
      port: 3000
      targetPort: 3000
  selector:
    app: hvnhi-web
